export const countryCodes = {
  AX: 'Aland Islands',
  AF: 'Afghanistan',
  DE: 'Germany',
  US: 'United States',
  AS: 'American Samoa',
  AD: 'Andorra',
  AI: 'Anguilla',
  AO: 'Angola',
  AG: 'Antigua and Barbuda',
  AR: 'Argentina',
  AL: 'Albania',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  PT1: 'Azores',
  BS: 'Bahamas',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Belarus',
  BE: 'Belgium',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermuda',
  BQ: 'BES Islands',
  BT: 'Bhutan',
  AE: 'United Arab Emirates',
  BO: 'Bolivia',
  BA: 'Bosnia and Herzegovina',
  BW: 'Botswana',
  BR: 'Brazil',
  BN: 'Brunei Darussalam',
  BG: 'Bulgaria',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  CV: 'Cape Verde',
  KY: 'Cayman Islands',
  GI: 'Cebelitarık',
  ES2: 'Ceuta',
  DZ: 'Algeria',
  DJ: 'Djibouti',
  CK: 'Cook Islands',
  TD: 'Chad',
  CZ: 'Czech Republic',
  CN: 'China',
  DK: 'Denmark',
  TL: 'Timor-Leste',
  DO: 'Dominican Republic',
  DM: 'Dominica',
  GQ: 'Equatorial Guinea',
  EC: 'Ecuador',
  ID: 'Indonesia',
  ER: 'Eritrea',
  AM: 'Armenia',
  MA: 'Morocco',
  FJ: 'Fiji',
  CI: 'Ivory Coast',
  PH: 'Philippines',
  FI: 'Finland',
  FR: 'France',
  GF: 'French Guiana',
  PF: 'French Polynesia',
  GA: 'Gabon',
  GB4: 'Wales',
  GM: 'Gambia',
  GH: 'Ghana',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  GD: 'Grenada',
  GT: 'Guatemala',
  GL: 'Greenland',
  GP: 'Guadeloupe',
  GU: 'Guam',
  GG: 'Guernsey',
  GY: 'Guyana',
  ZA: 'South Africa',
  KR: 'South Korea',
  GE: 'Georgia',
  HT: 'Haiti',
  HR: 'Croatia',
  IN: 'India',
  NL: 'Netherlands',
  HN: 'Honduras',
  IQ: 'Iraq',
  VG: 'British Virgin Islands',
  GB: 'United Kingdom',
  IE: 'Republic of Ireland',
  GB3: 'Scotland',
  ES: 'Spain (except Canary Islands,Ceuta and Melilla)',
  IL: 'Israel',
  SE: 'Sweden',
  CH: 'Switzerland',
  IT: 'Italy',
  IS: 'Iceland',
  JM: 'Jamaica',
  JP: 'Japan',
  JE: 'Jersey',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CA: 'Canada',
  ME: 'Montenegro',
  QA: 'Qatar',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KI: 'Kiribati',
  CO: 'Colombia',
  KM: 'Comoros',
  CG: 'Congo',
  CD: 'Democratic Republic of the Congo',
  FM1: 'Kosrae (Federated States of Micronesia)',
  CR: 'Costa Rica',
  KW: 'Kuwait',
  GB2: 'Northern Ireland',
  MP: 'Northern Mariana Islands',
  LA: 'Laos',
  LS: 'Lesotho',
  LV: 'Latvia',
  LR: 'Liberia',
  LY: 'Libya',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LB: 'Lebanon',
  LU: 'Luxembourg',
  MO: 'Macau',
  HU: 'Hungary',
  MG: 'Madagascar',
  MK: 'North Macedonia',
  MW: 'Malawi',
  MV: 'Maldives',
  MY: 'Malaysia',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Marshall Islands',
  YT: 'Mayotte',
  MX: 'Mexico',
  ES3: 'Melilla',
  EG: 'Egypt',
  FM: 'Federated States of Micronesia',
  MN: 'Mongolia',
  MD: 'Moldova',
  MC: 'Monaco',
  MS: 'Montserrat',
  MR: 'Mauritania',
  MU: 'Mauritius',
  MZ: 'Mozambique',
  MM: 'Myanmar',
  NA: 'Namibia',
  NP: 'Nepal',
  NE: 'Niger',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NO: 'Norway',
  CF: 'Central African Republic',
  UZ: 'Uzbekistan',
  PK: 'Pakistan',
  PW: 'Palau',
  PA: 'Panama',
  PG: 'Papua New Guinea',
  PY: 'Paraguay',
  PE: 'Peru',
  PL: 'Poland',
  FM2: 'Pohnpei (Federated States of Micronesia)',
  PT: 'Portugal',
  PR: 'Puerto Rico',
  RE: 'Réunion',
  RO: 'Romania',
  MP1: 'Rota (Northern Mariana Islands)',
  RW: 'Rwanda',
  RU1: 'Russia (Zip Code - Other)',
  RU0: 'Russia (Zip Code 101000-453999 & 460000-619999)',
  KN: 'Saint Kitts and Nevis',
  VC: 'Saint Vincent and the Grenadines',
  MP2: 'Saipan (Northern Mariana Islands)',
  WS: 'Samoa',
  SM: 'San Marino',
  SN: 'Senegal',
  SC: 'Seychelles',
  RS: 'Serbia',
  SL: 'Sierra Leone',
  SG: 'Singapore',
  SK: 'Slovakia',
  SI: 'Slovenia',
  BL: 'St. Barthelemy',
  GP1: 'St. Barthelemy',
  VI1: 'St. Croix (U.S. Virgin Islands)',
  AN3: 'St. Eustatius',
  VI2: 'St. John (U.S. Virgin Islands)',
  LC: 'St. Lucia',
  AN4: 'St. Maarten',
  SX: 'St. Maarten',
  SX1: 'St. Martin (Guadeloupe)',
  VI3: 'St. Thomas (U.S. Virgin Islands)',
  SB: 'Solomon Islands',
  LK: 'Sri Lanka',
  SR: 'Suriname',
  SA: 'Saudi Arabia',
  SZ: 'Swaziland',
  CL: 'Chile',
  TJ: 'Tajikistan',
  TZ: 'Tanzania',
  TH: 'Thailand',
  TW: 'Taiwan',
  MP3: 'Tinian (Northern Mariana Islands)',
  TG: 'Togo',
  TO: 'Tonga',
  VG1: 'Tortola (British Virgin Islands)',
  TT: 'Trinidad and Tobago',
  FM3: 'Truk (Federated States of Micronesia)',
  TN: 'Tunisia',
  TC: 'Turks and Caicos Islands',
  TV: 'Tuvalu',
  TM: 'Turkmenistan',
  UG: 'Uganda',
  UA: 'Ukraine',
  OM: 'Oman',
  VC1: 'Union Island (St. Vincent and the Grenadines)',
  UY: 'Uruguay',
  JO: 'Jordan',
  VU: 'Vanuatu',
  VE: 'Venezuela',
  VN: 'Vietnam',
  YE: 'Yemen',
  VI: 'US Virgin Islands',
  VG2: 'Virgin Gorda (British Virgin Islands)',
  WF: 'Wallis and Futuna Islands',
  FM4: 'Yap (Federated States of Micronesia)',
  NZ: 'New Zealand',
  GR: 'Greece',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
  KV: 'Kosovo',
  NC: 'New Caledonia',
  AN: 'Bonaire',
  CW: 'Curaçao',
  SV: 'Salvador',
  ES1: 'Canary Islands',
  IC: 'Canary Islands',
  CY: 'Cyprus',
  PT2: 'Madeira',
  MQ: 'Martinique',
  EE: 'Estonia',
  ET: 'Ethiopia',
  FO: 'Faroe Islands',
  PS: 'Gaza Strip',
  HK: 'Hong Kong',
  TR: 'Turkiye',
  IM: 'Isle of Man',
} as const
